export const INITIAL_CONTACTS = [
  {id:'c0',name:'Javier González',email:'jgonzalezb@acciona.com',company:'Acciona',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c1',name:'Raul Gomez',email:'rgomez@aena.es',company:'Aena',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c2',name:'patricia.lopez@alsa.es',email:'patricia.lopez@alsa.es',company:'Alsa',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c3',name:'Jose Estévez García',email:'joseantonio.estevez@alsa.es',company:'Alsa',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c4',name:'rafael.morales@astrazeneca.com',email:'rafael.morales@astrazeneca.com',company:'AstraZeneca',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c5',name:'rafael.jimenez1@astrazeneca.com',email:'rafael.jimenez1@astrazeneca.com',company:'AstraZeneca',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c6',name:'Miguel Lancha Luquero',email:'miguel.lancha@astrazeneca.com',company:'AstraZeneca',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c7',name:'gcallejo@atleticodemadrid.com',email:'gcallejo@atleticodemadrid.com',company:'Atlético de Madrid',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c8',name:'Lucía Prieto',email:'l.prieto@barcelo.com',company:'Barceló Hotel Group',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c9',name:'Raul González',email:'r.gonzalez@barcelo.com',company:'Barceló Hotel Group',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c10',name:'Oscar Palacios',email:'oscar.palacios@canarianhospitality.com',company:'Canarian Hospitality',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c11',name:'Alejandro Paez',email:'alejandro.paez@canarianhospitality.com',company:'Canarian Hospitality',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c12',name:'Francisco Fernandez',email:'francisco.fernandez@canarianhospitality.com',company:'Canarian Hospitality',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c13',name:'Germán Bautista',email:'gbautista@caser.es',company:'Caser',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c14',name:'mariajose.torquemada@cbre.com',email:'mariajose.torquemada@cbre.com',company:'CBRE',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c15',name:'Pedro Sánchez',email:'pedro.sanchez@cbre.com',company:'CBRE',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c16',name:'Arturo Carballo',email:'arturo.carballo@cbre.com',company:'CBRE',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c17',name:'Carlos Martín Carrión',email:'ccarrion@coca-cola.com',company:'Coca-Cola',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c18',name:'Timo Buetefisch',email:'timo@cooltra.com',company:'Cooltra',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c19',name:'Pablo Mancia',email:'pablo.mancia@delvy.es',company:'Delvy',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c20',name:'Patrick Gantier',email:'patrick.gantier@diageo.com',company:'Diageo',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c21',name:'Judit Faus Garriga',email:'judit.faus@dkvservicios.com',company:'DKV Seguros',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c22',name:'Carol Blázquez Gracía',email:'cblazquez@ecoalf.com',company:'Ecoalf',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c23',name:'santiago.bau@elcorteingles.es',email:'santiago.bau@elcorteingles.es',company:'El Corte Inglés',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c24',name:'David Gonzalez',email:'david.gonzalezmartinez@elcorteingles.es',company:'El Corte Inglés',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c25',name:'arturo.criado@elespanol.com',email:'arturo.criado@elespanol.com',company:'EL ESPAÑOL',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c26',name:'Daniel Muñoz',email:'daniel.munoz@elespanol.com',company:'EL ESPAÑOL',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c27',name:'Maria Antonia Muguerza Goya',email:'mmuguerza@erhardt.es',company:'Erhardt',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c28',name:'belen.grana@esic.edu',email:'belen.grana@esic.edu',company:'ESIC',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c29',name:'Jokin Urraza',email:'jurraza@planeta.es',company:'Grupo Planeta',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c30',name:'Jorge Pou',email:'jorge.x.pou@gsk.com',company:'GSK',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c31',name:'Maria Capezio',email:'maria.capezio@henkel.com',company:'Henkel',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c32',name:'Arturo Marzal Garcia',email:'arturo.marzal@homeserve.es',company:'HomeServe España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c33',name:'Josep Anyon',email:'josep@anyon.cat',company:'HomeServe España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c34',name:'María de la O Martínez',email:'mdmartinez@iberdrola.es',company:'Iberdrola',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c35',name:'Marta de Dalmases Herrero',email:'mdalmases@iberia.es',company:'Iberia',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c36',name:'Martin Beitia Salaberria',email:'mbeitia@iberia.es',company:'Iberia',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c37',name:'Rafael Murillo',email:'rmurillo@iberiacards.com',company:'iberiacards.com',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c38',name:'Alfonso Negrete',email:'alfonso.negrete@ingka.ikea.com',company:'IKEA',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c39',name:'Hanna Berenok',email:'hanna.berenok@impbrands.com',company:'Imperial Brands',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c40',name:'eherrera@kia.es',email:'eherrera@kia.es',company:'Kia España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c41',name:'Divar Eduardo',email:'edivar@kia.es',company:'Kia España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c42',name:'Álvaro De Sicart',email:'asicart@caixabank.com',company:'La Caixa',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c43',name:'Veronica Suarez Alvarez-Hevia',email:'veronica.suarez@logista.com',company:'Logista',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c44',name:'Juan Carlos Moro',email:'juancarlos.moro@logista.com',company:'Logista',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c45',name:'Miguel Ángel De Miguel Martín',email:'mmiguelm@mahou-sanmiguel.com',company:'Mahou San Miguel',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c46',name:'Guillermo Arrieta',email:'garrieta@mahou-sanmiguel.com',company:'Mahou San Miguel',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c47',name:'Guillermo De Pedro',email:'gdepedror@mahou-sanmiguel.com',company:'Mahou San Miguel',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c48',name:'Alejandro Arranz',email:'aarranzs@mahou-sanmiguel.com',company:'Mahou San Miguel',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c49',name:'Marta Mateu Vilalta',email:'marta.mateu@mango.com',company:'Mango',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c50',name:'Begoña Molina',email:'begoamo@mapfre.com',company:'Mapfre',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c51',name:'Irene Fernandez López',email:'fliren1@mapfre.com',company:'Mapfre',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c52',name:'Arantxa Rodriguez',email:'rmaran3@mapfre.com',company:'Mapfre',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c53',name:'cvazquezb@mediaset.es',email:'cvazquezb@mediaset.es',company:'Megamedia / Mediaset',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c54',name:'jamoreno@mediaset.es',email:'jamoreno@mediaset.es',company:'Megamedia / Mediaset',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c55',name:'Cecilia Mangisch',email:'cmangisch@megamedia.es',company:'Megamedia / Mediaset',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c56',name:'Jorge Pérez de Leza',email:'jpdeleza@metrovacesa.com',company:'Metrovacesa',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c57',name:'Ernesto Mateo Hernández',email:'emateo@mutua.es',company:'Mutua Madrileña',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c58',name:'Soledad García Sánchez',email:'sgarcias@mutua.es',company:'Mutua Madrileña',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c59',name:'Javiera Ortega',email:'jc.ortega@gcoventures.com',company:'Occident Catalana Occidente',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c60',name:'Carmen Lendoiro',email:'carmen.lendoiro@pascualinnoventures.com',company:'Pascual',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c61',name:'Cristina Sanchez Rams',email:'csanchez@pastasgallo.es',company:'Pastas Gallo',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c62',name:'Néstor Nava',email:'nnava@pastasgallo.es',company:'Pastas Gallo',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c63',name:'Gelsomino Centanni',email:'gelsomino.centanni@pfizer.com',company:'Pfizer',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c64',name:'Andreu Tobella',email:'andreu.tobella@portaventura.es',company:'PortAventura',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c65',name:'David Garcia',email:'david.garcia@portaventura.com',company:'PortAventura World',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c66',name:'Mireia Bove',email:'mireiabove@hotmail.com',company:'PortAventura World',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c67',name:'loida.sanchez@quironsalud.es',email:'loida.sanchez@quironsalud.es',company:'quirónsalud',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c68',name:'Román apezteguia',email:'roman.apezteguia@racc.es',company:'RACC',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c69',name:'Ignacio Polvorinos',email:'ignacio_polvorinos@race.es',company:'RACE',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c70',name:'Matteo Villa',email:'matteo.villa@realemutua.it',company:'Reale Seguros',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c71',name:'Patricia Torpedo Moreno',email:'patricia.torpedomoreno@reale.es',company:'Reale Seguros',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c72',name:'Carlos Bermudez',email:'cbermudezg@repsol.com',company:'Repsol',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c73',name:'Alfonso Flores',email:'alfonso.flores@repsol.com',company:'Repsol',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c74',name:'Sandra Blázquez Borrás',email:'sblazquezb@repsol.com',company:'Repsol',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c75',name:'diego.menz@roca.net',email:'diego.menz@roca.net',company:'Roca Sanitario',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c76',name:'Daniel Valverde',email:'daniel.valverde@roca.net',company:'Roca Sanitario',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c77',name:'Cristina Ortigosa',email:'cristina.ortigosa@roche.com',company:'Roche',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c78',name:'Alberto Guijarro Gomez',email:'aguijarrog@sanitas.es',company:'Sanitas',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c79',name:'Diego Gutierrez',email:'diego.gutierrez@gruposantander.com',company:'Santander Seguros',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c80',name:'mariaantonia.fontiverio@seat.es',email:'mariaantonia.fontiverio@seat.es',company:'SEAT España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c81',name:'Laura Vidal Tost',email:'laura.vidal@seat.es',company:'SEAT España',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c82',name:'Alberto De la Capilla Heusch',email:'alberto.delacapilla@securitasdirect.es',company:'Securitas Direct / Verisure',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c83',name:'Rafael Miranda Arzac',email:'rafael.miranda@verisure.com',company:'Securitas Direct / Verisure',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c84',name:'jgonzalez@segurcaixaadeslas.es',email:'jgonzalez@segurcaixaadeslas.es',company:'SegurCaixa Adeslas',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c85',name:'Sebastian Del Busto',email:'bustos@segurcaixaadeslas.es',company:'SegurCaixa Adeslas',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c86',name:'arranzb@segurcaixaadeslas.es',email:'arranzb@segurcaixaadeslas.es',company:'SegurCaixa Adeslas',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c87',name:'Miguel Chaves Álvarez',email:'mchavesalvarez@serveo.com',company:'Serveo',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c88',name:'David Sastre',email:'david.sastre@seur.net',company:'Seur',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c89',name:'Alejandro Gonzalez',email:'alejandro.gonzalez@sgs.com',company:'SGS',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c90',name:'Sara Hidalgo',email:'sara.hidalgo@sgs.com',company:'SGS',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c91',name:'Pablo Garcia',email:'pablo.garcia@sgs.com',company:'SGS',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c92',name:'Jesus Benassar',email:'jesus.bennasar@sgs.com',company:'SGS',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c93',name:'Jose Maria Hernandez-Sampelayo Matos',email:'josemaria.hernandez@sgs.com',company:'SGS',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c94',name:'Nasser F. Alturaifi',email:'nalturaifi@stc.com.sa',company:'stc',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c95',name:'Abdullah A. Alabdrabalreda',email:'aalabdrabalreda@stc.com.sa',company:'stc',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c96',name:'Itziar Domecp',email:'idomecqo@telpark.com',company:'Telpark',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c97',name:'Luis Blanco',email:'lblanco@telpark.com',company:'Telpark',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c98',name:'Beatriz Reverter',email:'breverter@coca-colacompany.com',company:'The Coca-Cola Company',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c99',name:'xrebes@tous.com',email:'xrebes@tous.com',company:'Tous Jewelry',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c100',name:'mcosta@tous.com',email:'mcosta@tous.com',company:'Tous Jewelry',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c101',name:'Geoffroy Level',email:'geoffroy.level@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c102',name:'Alexis Veron',email:'alexis.veron@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c103',name:'Dominique Hautbois',email:'dominique.hautbois@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c104',name:'Ricardo Lizcano',email:'ricardo.lizcano@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c105',name:'Enrique Bayon',email:'enrique.bayon@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c106',name:'carlos.sanchez-lastra@urw.com',email:'carlos.sanchez-lastra@urw.com',company:'Unibail-Rodamco-Westfield',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c107',name:'Jorge Álvarez Cercadilla',email:'jorge.alvarezcercadillo@uam.es',company:'Universidad Autónoma',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c108',name:'sara preciado',email:'sarapreciado@ub.edu',company:'Universitat de Barcelona',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c109',name:'Blanca Almendro',email:'blalmendro@valorizasm.com',company:'Valoriza',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c110',name:'David Redondo',email:'dredondo@valorizasm.com',company:'Valoriza',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c111',name:'Laura Ros Voerhoven',email:'laura.ros@volkswagen.es',company:'Volkswagen',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c112',name:'Patrick Schinnerling',email:'patrick.schinnerling@volkswagengroup.es',company:'Volkswagen',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c113',name:'Marta Ensenat',email:'marta.ensenat@volkswagengroup.es',company:'Volkswagengroup',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c114',name:'Eleonor Hedström',email:'eleonor.hedstrom@wartsila.com',company:'Wärtsilä',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c115',name:'joao.almeida@yum.com',email:'joao.almeida@yum.com',company:'Yum! Brands',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c116',name:'Rui',email:'rui@busup.com',company:'BusUp',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c117',name:'Andres Goicochea',email:'andrescasal@wetaca.com',company:'Wetaca',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c118',name:'Amadeo',email:'amedeo@ensospaces.com',company:'Enso Spaces',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c119',name:'Blanca Piedrola Baez',email:'bpiedrola@cash-converters.es',company:'Cash Converters',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c120',name:'Guillermo Rodriguez',email:'grodriguez@collegiate-ac.com',company:'Collegiate-ac',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c121',name:'Juan Francisco Sanjuán Gallego',email:'jsanjuan@aevosaludbelleza.com',company:'Clinicas Aevo',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c122',name:'Carlos Rosales',email:'carlos.rosales@we-online.com',company:'Wurth',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c123',name:'Alice Alberti',email:'alicea@cocunat.com',company:'Cocunat',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c124',name:'Miguel Ortega',email:'miguelortega@clubestudiantes.com',company:'Club Estudiantes',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c125',name:'María Batista',email:'mbatista@clubestudiantes.com',company:'Club Estudiantes',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c126',name:'Jesús Iglesias',email:'jiglesias@realbetisbalompie.es',company:'Real Betis',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c127',name:'maria',email:'mmellado@elconfidencial.com',company:'El Confidencial',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c128',name:'ELENA',email:'elena.martinez@codere.com',company:'CODERE',direct:false,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c129',name:'Pitu Cachau',email:'maria.cachau@homeclub.com',company:'Homeclub',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c130',name:'Carlota Redon',email:'carlotaredon.miguelr@santalucia.es',company:'Santa Lucia',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
  {id:'c131',name:'Blanco, Paloma',email:'paloma.blanco@hyatt.com',company:'Hyatt Gran Via',direct:true,status:0,notes:'',followups:[],role:'',lastContact:null},
];

export const STAGES = ['Sin contactar','Email enviado','Respondió','Reunión agendada','Propuesta enviada','Descartado','Cerrado ✓'];
export const STAGE_COLORS = ['gray','blue','purple','amber','green','red','teal'];
